# Generated by Django 5.2.7 on 2025-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('description', models.TextField(verbose_name='عنوان/تیتری کوتاه')),
            ],
        ),
    ]
