# Generated by Django 5.2.7 on 2025-11-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'کار هایی که میتونم انجام بدم', 'verbose_name_plural': 'کار'},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='کار ها'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='کار هایی که میتونم انجام بدم'),
        ),
    ]
