# Generated by Django 5.2.7 on 2025-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_options_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس\u200cها'},
        ),
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='آیکون (اختیاری)'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان سرویس'),
        ),
    ]
