# Generated by Django 5.2.7 on 2025-11-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='مدرک')),
                ('university', models.CharField(max_length=200, verbose_name='موسسه/دانشگاه')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='بازه زمانی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تحصیلات',
                'verbose_name_plural': 'تحصیلات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=200, verbose_name='شرکت')),
                ('start_year', models.CharField(max_length=20, verbose_name='شروع (مثال: 1399)')),
                ('end_year', models.CharField(blank=True, max_length=20, verbose_name='پایان (یا اکنون)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سوابق کاری',
                'verbose_name_plural': 'سوابق کاری',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('tech', models.CharField(blank=True, max_length=200, verbose_name='تکنولوژی\u200cها')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('link', models.URLField(blank=True, verbose_name='لینک (اختیاری)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان/تیتری کوتاه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=50, verbose_name='تلفن')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('about', models.TextField(blank=True, verbose_name='درباره من')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='عکس پروفایل')),
                ('header_bg', models.CharField(blank=True, max_length=200, verbose_name='گرادیان هدر (اختیاری)')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('level', models.PositiveSmallIntegerField(default=50, verbose_name='درصد تسلط (0-100)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
